# This is a basic workflow to help you get started with Actions

name: Main CI

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    tags: 
      - 'v*'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-whale-demo:latest
          tags: ghcr.io/phoenix91/my-docker-whale-demo:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-whale-demo:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-whale-demo:buildcache,mode=max
          
